services:
  selenoid:
    image: aerokube/selenoid:1.11.3
    container_name: selenoid-my
    ports:
      - "4444:4444"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./browsers.json:/etc/selenoid/browsers.json"
    networks:
      - selenoid_net

  selenoid-ui:
    image: aerokube/selenoid-ui:1.10.11
    container_name: selenoid-ui-my
    ports:
      - "8080:8080"
    depends_on:
      - selenoid
    networks:
      - selenoid_net
    command: ["--selenoid-uri", "http://selenoid:4444"]

  tests:
    build: .
    container_name: test-runner
    depends_on:
      - selenoid
    environment:
      - SELENOID_URL=http://selenoid:4444
    networks:
      - selenoid_net

networks:
  selenoid_net:
    external: true
